"""Add FacebookPageToken

Revision ID: 0e298ca498ed
Revises: 6919c52c967c
Create Date: 2026-09-15 17:21:04.249295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e298ca498ed'
down_revision: Union[str, Sequence[str], None] = '6919c52c967c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facebook_page_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('page_id', sa.String(length=128), nullable=False),
    sa.Column('page_name', sa.String(length=255), nullable=True),
    sa.Column('encrypted_token', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'page_id', name='uq_user_page')
    )
    op.create_index(op.f('ix_facebook_page_tokens_page_id'), 'facebook_page_tokens', ['page_id'], unique=False)
    op.create_index(op.f('ix_facebook_page_tokens_user_id'), 'facebook_page_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facebook_page_tokens_user_id'), table_name='facebook_page_tokens')
    op.drop_index(op.f('ix_facebook_page_tokens_page_id'), table_name='facebook_page_tokens')
    op.drop_table('facebook_page_tokens')
    # ### end Alembic commands ###
