"""add_template_id_to_extracted_media

Revision ID: 31c02e0c8a1b
Revises: 6a4a8256c20f
Create Date: 2026-09-29 01:02:13.130376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31c02e0c8a1b'
down_revision: Union[str, Sequence[str], None] = '6a4a8256c20f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracted_media', sa.Column('template_id', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_extracted_media_template_id'), 'extracted_media', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_media_template_id'), table_name='extracted_media')
    op.drop_column('extracted_media', 'template_id')
    # ### end Alembic commands ###
