"""add_users_and_media_models

Revision ID: 6919c52c967c
Revises: 64695230881d
Create Date: 2026-09-13 02:22:32.041732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6919c52c967c'
down_revision: Union[str, Sequence[str], None] = '64695230881d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('api_base_url', sa.String(length=512), nullable=True),
    sa.Column('api_endpoint_path', sa.String(length=255), nullable=True),
    sa.Column('model_version', sa.String(length=255), nullable=True),
    sa.Column('auth_env_var', sa.String(length=64), nullable=True),
    sa.Column('is_async_poll', sa.Boolean(), nullable=False),
    sa.Column('poll_endpoint_path', sa.String(length=255), nullable=True),
    sa.Column('poll_status_field', sa.String(length=128), nullable=True),
    sa.Column('poll_success_value', sa.String(length=64), nullable=True),
    sa.Column('poll_failed_value', sa.String(length=64), nullable=True),
    sa.Column('poll_timeout_s', sa.Integer(), nullable=False),
    sa.Column('poll_interval_s', sa.Integer(), nullable=False),
    sa.Column('response_extraction_config_json', sa.Text(), nullable=True),
    sa.Column('returns_base64', sa.Boolean(), nullable=False),
    sa.Column('default_width', sa.Integer(), nullable=True),
    sa.Column('default_height', sa.Integer(), nullable=True),
    sa.Column('max_outputs', sa.Integer(), nullable=False),
    sa.Column('default_params_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_models_name'), 'media_models', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('google_id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('media_generations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('num_outputs', sa.Integer(), nullable=False),
    sa.Column('extra_params_json', sa.Text(), nullable=True),
    sa.Column('result_urls', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('elapsed_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['media_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_generations_model_id'), 'media_generations', ['model_id'], unique=False)
    op.create_index(op.f('ix_media_generations_user_id'), 'media_generations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_generations_user_id'), table_name='media_generations')
    op.drop_index(op.f('ix_media_generations_model_id'), table_name='media_generations')
    op.drop_table('media_generations')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_media_models_name'), table_name='media_models')
    op.drop_table('media_models')
    # ### end Alembic commands ###
