"""Add ProviderAPIKey table

Revision ID: 6a4a8256c20f
Revises: f7d4613214a6
Create Date: 2026-09-26 01:17:14.766530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a4a8256c20f'
down_revision: Union[str, Sequence[str], None] = 'f7d4613214a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('encrypted_key', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('requests_today', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'label', name='uq_provider_label')
    )
    op.create_index(op.f('ix_provider_api_keys_priority'), 'provider_api_keys', ['priority'], unique=False)
    op.create_index(op.f('ix_provider_api_keys_provider'), 'provider_api_keys', ['provider'], unique=False)
    op.alter_column('tts_jobs', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tts_jobs', 'title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_provider_api_keys_provider'), table_name='provider_api_keys')
    op.drop_index(op.f('ix_provider_api_keys_priority'), table_name='provider_api_keys')
    op.drop_table('provider_api_keys')
    # ### end Alembic commands ###
