"""add extracted_media table

Revision ID: b825376915a5
Revises: 0e298ca498ed
Create Date: 2026-09-21 17:55:27.102942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b825376915a5'
down_revision: Union[str, Sequence[str], None] = '0e298ca498ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extracted_media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('item_id', sa.String(length=128), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_media_item_id'), 'extracted_media', ['item_id'], unique=False)
    op.create_index(op.f('ix_extracted_media_user_id'), 'extracted_media', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_media_user_id'), table_name='extracted_media')
    op.drop_index(op.f('ix_extracted_media_item_id'), table_name='extracted_media')
    op.drop_table('extracted_media')
    # ### end Alembic commands ###
