"""app/api/v1/audio/router.py — Audio Text-to-Speech (TTS) endpoints."""

import logging
from fastapi import APIRouter, Depends, HTTPException, Response, status
from app.api.v1.audio.schemas import TTSRequest
from app.core.auth import get_current_api_key
from app.models.db_models import AccessAPIKey
from app.services.tts_service import generate_speech

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/audio", tags=["audio"])


@router.post(
    "/speech",
    summary="Generate speech audio from text using Kokoro TTS",
    response_class=Response,
    responses={
        200: {
            "content": {"audio/wav": {}},
            "description": "Returns raw WAV audio stream generated by Kokoro TTS.",
        }
    },
)
@router.post("/tts", include_in_schema=False)
async def generate_speech_endpoint(
    req: TTSRequest,
    api_key: AccessAPIKey | None = Depends(get_current_api_key),
) -> Response:
    """
    Generate speech audio from input text using Kokoro-82M ONNX model.
    Audio inference is executed asynchronously in a worker thread pool via asyncio.to_thread().
    """
    try:
        wav_bytes, sample_rate = await generate_speech(
            text=req.text,
            voice=req.voice,
            speed=req.speed,
            lang=req.lang,
        )
        return Response(
            content=wav_bytes,
            media_type="audio/wav",
            headers={
                "Content-Disposition": "attachment; filename=speech.wav",
                "X-Sample-Rate": str(sample_rate),
            },
        )
    except FileNotFoundError as exc:
        logger.error("Kokoro TTS model files not found: %s", exc)
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=str(exc),
        ) from exc
    except ValueError as exc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(exc),
        ) from exc
    except Exception as exc:
        logger.error("Error generating speech audio: %s", exc, exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Audio speech generation failed: {str(exc)}",
        ) from exc
